CREATE DATABASE IF NOT EXISTS ict361_lab_db;
USE ict361_lab_db;

CREATE TABLE IF NOT EXISTS Accounts (
    Account_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'student',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);